apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: catttt
spec:
  template:
    spec:
      containers:
        - image: index.docker.io/nikogianna19/test:2c0797ed9856d3b236fd353e3874f8a134e5b666
          ports:
            - containerPort: 8080
