apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: catttt
spec:
  template:
    spec:
      containers:
        - image: index.docker.io/nikogianna19/test:5bae8685b6a30e0e6910b3463aa589db3cd62755
          ports:
            - containerPort: 8080
